┌──────────────────────────────┐
│ STEP 4: Label Analysis       │
├──────────────────────────────┤
│ # classes                    │
│ samples/class                │
│ class imbalance              │
│ rare classes                 │
└──────────────┬───────────────┘

In [1]:
# ============================================================
# CISLR — STEP 4
# LABEL ANALYSIS
# ============================================================
#
# Purpose:
#   Analyze the class/label distribution of the CISLR dataset.
#
# Checks:
#   1. Number of classes
#   2. Samples per class
#   3. Class imbalance
#   4. Rare classes
#
# Input:
#   Step 2 -> video_mapping.csv
#
# Output:
#   label_analysis.csv
#   rare_classes.csv
# ============================================================

print("=" * 80)
print("CISLR — STEP 4: LABEL ANALYSIS")
print("=" * 80)

================================================================================
CISLR — STEP 4: LABEL ANALYSIS
================================================================================

CELL 2 — Load Step 2 output

In [3]:
# ============================================================
# CELL 2 — LOAD STEP 2 OUTPUT
# ============================================================

from pathlib import Path
import pandas as pd
cislr_research="/home/dipshikha/Music/cao/CISLR_RESEARCH"
mapping_file = (
    Path(cislr_research)
    / "processed"
    / "video_mapping.csv"
)

video_metadata_df = pd.read_csv(mapping_file)

print("Loaded:", mapping_file)
print("Rows:", len(video_metadata_df))

Loaded: /home/dipshikha/Music/cao/CISLR_RESEARCH/processed/video_mapping.csv
Rows: 7050

CELL 3 — Verify the label column

In [4]:
# ============================================================
# CELL 3 — VERIFY LABEL COLUMN
# ============================================================

print("Available columns:")
print(video_metadata_df.columns.tolist())

if "gloss" not in video_metadata_df.columns:
    raise ValueError(
        "The 'gloss' column was not found in video_mapping.csv."
    )

print("\nPASS — 'gloss' column found.")

Available columns:
['uid', 'gloss', 'duration', 'category', 'video_exists', 'video_path']

PASS — 'gloss' column found.

CELL 4 — Clean labels for analysis

In [5]:
# ============================================================
# CELL 4 — LABEL CLEANING
# ============================================================

label_df = video_metadata_df.copy()

label_df["gloss"] = (
    label_df["gloss"]
    .astype(str)
    .str.strip()
)

# Check for empty labels
empty_labels = (
    label_df["gloss"].isna()
    | (label_df["gloss"] == "")
    | (label_df["gloss"].str.lower() == "nan")
)

print("=" * 80)
print("LABEL VALIDATION")
print("=" * 80)

print("Total samples:", len(label_df))
print("Empty/missing labels:", empty_labels.sum())

================================================================================
LABEL VALIDATION
================================================================================
Total samples: 7050
Empty/missing labels: 1

CELL 5 — Number of classes

In [7]:
# ============================================================
# CELL 5 — NUMBER OF CLASSES
# ============================================================

valid_labels = label_df.loc[
    ~empty_labels,
    "gloss"
]

num_classes = valid_labels.nunique()

print("=" * 80)
print("NUMBER OF CLASSES")
print("=" * 80)

print("Number of unique classes:", num_classes)

================================================================================
NUMBER OF CLASSES
================================================================================
Number of unique classes: 4764

CELL 6 — Samples per class

In [8]:
# ============================================================
# CELL 6 — SAMPLES PER CLASS
# ============================================================

class_counts = (
    valid_labels
    .value_counts()
    .sort_values(ascending=False)
)

print("=" * 80)
print("SAMPLES PER CLASS")
print("=" * 80)

print("Total classes:", len(class_counts))

display(
    class_counts.to_frame("sample_count")
)

================================================================================
SAMPLES PER CLASS
================================================================================
Total classes: 4764

            sample_count
gloss
monday                13
thursday              11
interest              10
pencil                 9
friday                 9
...                  ...
aircel                 1
keyhole                1
postpone               1
festivals              1
good night             1

[4764 rows x 1 columns]

CELL 7 — Basic class distribution statistics

In [9]:
# ============================================================
# CELL 7 — CLASS DISTRIBUTION STATISTICS
# ============================================================

class_distribution_stats = class_counts.describe()

print("=" * 80)
print("CLASS DISTRIBUTION STATISTICS")
print("=" * 80)

display(class_distribution_stats)

================================================================================
CLASS DISTRIBUTION STATISTICS
================================================================================

count    4764.000000
mean        1.479639
std         0.967998
min         1.000000
25%         1.000000
50%         1.000000
75%         2.000000
max        13.000000
Name: count, dtype: float64

CELL 8 — Most frequent classes

In [10]:
# ============================================================
# CELL 8 — MOST FREQUENT CLASSES
# ============================================================

top_classes = class_counts.head(20)

print("=" * 80)
print("TOP 20 MOST FREQUENT CLASSES")
print("=" * 80)

display(
    top_classes.to_frame("sample_count")
)

================================================================================
TOP 20 MOST FREQUENT CLASSES
================================================================================

           sample_count
gloss
monday               13
thursday             11
interest             10
pencil                9
friday                9
mother                8
yellow                8
tuesday               8
christmas             8
increase              7
iron                  7
light                 7
angry                 7
bill                  7
name                  7
sunday                7
india                 7
rubber                7
date                  7
wednesday             7

CELL 9 — Rare class definition

In [11]:
# ============================================================
# CELL 9 — DEFINE RARE CLASSES
# ============================================================

RARE_CLASS_THRESHOLD = 20

rare_classes = class_counts[
    class_counts < RARE_CLASS_THRESHOLD
]

print("=" * 80)
print("RARE CLASS ANALYSIS")
print("=" * 80)

print(
    "Rare class threshold:",
    RARE_CLASS_THRESHOLD,
    "samples"
)

print(
    "Number of rare classes:",
    len(rare_classes)
)

print(
    "Samples belonging to rare classes:",
    rare_classes.sum()
)

================================================================================
RARE CLASS ANALYSIS
================================================================================
Rare class threshold: 20 samples
Number of rare classes: 4764
Samples belonging to rare classes: 7049

CELL 10 — Display rare classes

In [12]:
# ============================================================
# CELL 10 — RARE CLASS LIST
# ============================================================

print("=" * 80)
print("RARE CLASSES")
print("=" * 80)

if len(rare_classes) == 0:

    print("No classes have fewer than",
          RARE_CLASS_THRESHOLD,
          "samples.")

else:

    display(
        rare_classes
        .to_frame("sample_count")
    )

================================================================================
RARE CLASSES
================================================================================

            sample_count
gloss
monday                13
thursday              11
interest              10
pencil                 9
friday                 9
...                  ...
aircel                 1
keyhole                1
postpone               1
festivals              1
good night             1

[4764 rows x 1 columns]

CELL 11 — Class imbalance ratio

In [13]:
# ============================================================
# CELL 11 — CLASS IMBALANCE RATIO
# ============================================================

max_samples = class_counts.max()
min_samples = class_counts.min()

imbalance_ratio = max_samples / min_samples

print("=" * 80)
print("CLASS IMBALANCE")
print("=" * 80)

print("Largest class :", max_samples)
print("Smallest class:", min_samples)

print(
    "Imbalance ratio:",
    round(imbalance_ratio, 2)
)

================================================================================
CLASS IMBALANCE
================================================================================
Largest class : 13
Smallest class: 1
Imbalance ratio: 13.0

CELL 12 — Majority/minority comparison

In [14]:
# ============================================================
# CELL 12 — MAJORITY / MINORITY ANALYSIS
# ============================================================

majority_class = class_counts.idxmax()
minority_class = class_counts.idxmin()

print("=" * 80)
print("MAJORITY / MINORITY CLASSES")
print("=" * 80)

print(
    "Majority class:",
    majority_class,
    "→",
    max_samples,
    "samples"
)

print(
    "Minority class:",
    minority_class,
    "→",
    min_samples,
    "samples"
)

================================================================================
MAJORITY / MINORITY CLASSES
================================================================================
Majority class: monday → 13 samples
Minority class: divorce petition → 1 samples

CELL 13 — Percentage contribution of each class

In [15]:
# ============================================================
# CELL 13 — CLASS PERCENTAGES
# ============================================================

total_samples = class_counts.sum()

class_percentage = (
    class_counts / total_samples * 100
)

label_distribution_df = pd.DataFrame({
    "sample_count": class_counts,
    "percentage": class_percentage.round(4)
})

print("=" * 80)
print("CLASS DISTRIBUTION")
print("=" * 80)

display(label_distribution_df)

================================================================================
CLASS DISTRIBUTION
================================================================================

            sample_count  percentage
gloss
monday                13      0.1844
thursday              11      0.1561
interest              10      0.1419
pencil                 9      0.1277
friday                 9      0.1277
...                  ...         ...
aircel                 1      0.0142
keyhole                1      0.0142
postpone               1      0.0142
festivals              1      0.0142
good night             1      0.0142

[4764 rows x 2 columns]

CELL 14 — Final label analysis summary

In [16]:
# ============================================================
# CELL 14 — LABEL ANALYSIS SUMMARY
# ============================================================

summary = {
    "total_samples": int(total_samples),
    "number_of_classes": int(num_classes),
    "minimum_samples_per_class": int(min_samples),
    "maximum_samples_per_class": int(max_samples),
    "mean_samples_per_class": float(class_counts.mean()),
    "median_samples_per_class": float(class_counts.median()),
    "imbalance_ratio": float(imbalance_ratio),
    "rare_class_threshold": RARE_CLASS_THRESHOLD,
    "number_of_rare_classes": int(len(rare_classes)),
    "samples_in_rare_classes": int(rare_classes.sum()),
    "missing_or_empty_labels": int(empty_labels.sum())
}

summary_df = pd.DataFrame(
    summary.items(),
    columns=["metric", "value"]
)

print("=" * 80)
print("LABEL ANALYSIS SUMMARY")
print("=" * 80)

display(summary_df)

================================================================================
LABEL ANALYSIS SUMMARY
================================================================================

                       metric        value
0               total_samples  7049.000000
1           number_of_classes  4764.000000
2   minimum_samples_per_class     1.000000
3   maximum_samples_per_class    13.000000
4      mean_samples_per_class     1.479639
5    median_samples_per_class     1.000000
6             imbalance_ratio    13.000000
7        rare_class_threshold    20.000000
8      number_of_rare_classes  4764.000000
9     samples_in_rare_classes  7049.000000
10    missing_or_empty_labels     1.000000

CELL 15 — Save complete label analysis

In [17]:
# ============================================================
# CELL 15 — SAVE LABEL ANALYSIS
# ============================================================

output_file = (
    Path(cislr_research)
    / "processed"
    / "label_analysis.csv"
)

label_distribution_df.to_csv(
    output_file,
    index_label="gloss"
)

print("=" * 80)
print("LABEL ANALYSIS SAVED")
print("=" * 80)

print(output_file)

================================================================================
LABEL ANALYSIS SAVED
================================================================================
/home/dipshikha/Music/cao/CISLR_RESEARCH/processed/label_analysis.csv

CELL 16 — Save rare classes

In [18]:
# ============================================================
# CELL 16 — SAVE RARE CLASS REPORT
# ============================================================

rare_file = (
    Path(cislr_research)
    / "processed"
    / "rare_classes.csv"
)

rare_classes.to_frame(
    "sample_count"
).to_csv(
    rare_file,
    index_label="gloss"
)

print("Rare-class report saved:")
print(rare_file)

Rare-class report saved:
/home/dipshikha/Music/cao/CISLR_RESEARCH/processed/rare_classes.csv

CELL 17 — Final PASS / REVIEW

In [19]:
# ============================================================
# CELL 17 — STEP 4 FINAL STATUS
# ============================================================

print("=" * 80)
print("STEP 4 — FINAL STATUS")
print("=" * 80)

if empty_labels.sum() == 0:

    print("PASS — No missing/empty labels.")

else:

    print(
        "REVIEW REQUIRED —",
        empty_labels.sum(),
        "samples have missing/empty labels."
    )

print()
print("Number of classes :", num_classes)
print("Total samples     :", total_samples)
print("Rare classes      :", len(rare_classes))
print("Imbalance ratio   :", round(imbalance_ratio, 2))

================================================================================
STEP 4 — FINAL STATUS
================================================================================
REVIEW REQUIRED — 1 samples have missing/empty labels.

Number of classes : 4764
Total samples     : 7049
Rare classes      : 4764
Imbalance ratio   : 13.0