In [1]:
# ============================================================
# CISLR — STEP 5
# SPLIT VERIFICATION & DATA LEAKAGE ANALYSIS
# ============================================================
#
# Purpose:
#   Verify that the official CISLR test set is correctly
#   separated from the training data and identify possible
#   sources of data leakage.
#
# Checks:
#   1. Official test-set membership
#   2. Train/test UID overlap
#   3. Duplicate UID entries
#   4. Duplicate video content
#   5. UID ↔ filename consistency
#   6. Potential data leakage
#
# Inputs:
#   Step 2 -> video_mapping.csv
#   CISLR  -> test.csv
#
# Outputs:
#   split_verification.csv
#   leakage_report.csv
# ============================================================

print("=" * 80)
print("CISLR — STEP 5: SPLIT VERIFICATION")
print("=" * 80)

================================================================================
CISLR — STEP 5: SPLIT VERIFICATION
================================================================================

CELL 2 — Load previous notebook outputs

In [3]:
# ============================================================
# CELL 2 — LOAD PREVIOUS PIPELINE OUTPUTS
# ============================================================

%run step4.ipynb

print("\nPrevious pipeline information loaded.")

================================================================================
CISLR — STEP 4: LABEL ANALYSIS
================================================================================
Loaded: /home/dipshikha/Music/cao/CISLR_RESEARCH/processed/video_mapping.csv
Rows: 7050
Available columns:
['uid', 'gloss', 'duration', 'category', 'video_exists', 'video_path']

PASS — 'gloss' column found.
================================================================================
LABEL VALIDATION
================================================================================
Total samples: 7050
Empty/missing labels: 1
================================================================================
NUMBER OF CLASSES
================================================================================
Number of unique classes: 4764
================================================================================
SAMPLES PER CLASS
================================================================================
Total classes: 4764

            sample_count
gloss
monday                13
thursday              11
interest              10
pencil                 9
friday                 9
...                  ...
aircel                 1
keyhole                1
postpone               1
festivals              1
good night             1

[4764 rows x 1 columns]

================================================================================
CLASS DISTRIBUTION STATISTICS
================================================================================

count    4764.000000
mean        1.479639
std         0.967998
min         1.000000
25%         1.000000
50%         1.000000
75%         2.000000
max        13.000000
Name: count, dtype: float64

================================================================================
TOP 20 MOST FREQUENT CLASSES
================================================================================

           sample_count
gloss
monday               13
thursday             11
interest             10
pencil                9
friday                9
mother                8
yellow                8
tuesday               8
christmas             8
increase              7
iron                  7
light                 7
angry                 7
bill                  7
name                  7
sunday                7
india                 7
rubber                7
date                  7
wednesday             7

================================================================================
RARE CLASS ANALYSIS
================================================================================
Rare class threshold: 20 samples
Number of rare classes: 4764
Samples belonging to rare classes: 7049
================================================================================
RARE CLASSES
================================================================================

            sample_count
gloss
monday                13
thursday              11
interest              10
pencil                 9
friday                 9
...                  ...
aircel                 1
keyhole                1
postpone               1
festivals              1
good night             1

[4764 rows x 1 columns]

================================================================================
CLASS IMBALANCE
================================================================================
Largest class : 13
Smallest class: 1
Imbalance ratio: 13.0
================================================================================
MAJORITY / MINORITY CLASSES
================================================================================
Majority class: monday → 13 samples
Minority class: divorce petition → 1 samples
================================================================================
CLASS DISTRIBUTION
================================================================================

            sample_count  percentage
gloss
monday                13      0.1844
thursday              11      0.1561
interest              10      0.1419
pencil                 9      0.1277
friday                 9      0.1277
...                  ...         ...
aircel                 1      0.0142
keyhole                1      0.0142
postpone               1      0.0142
festivals              1      0.0142
good night             1      0.0142

[4764 rows x 2 columns]

================================================================================
LABEL ANALYSIS SUMMARY
================================================================================

                       metric        value
0               total_samples  7049.000000
1           number_of_classes  4764.000000
2   minimum_samples_per_class     1.000000
3   maximum_samples_per_class    13.000000
4      mean_samples_per_class     1.479639
5    median_samples_per_class     1.000000
6             imbalance_ratio    13.000000
7        rare_class_threshold    20.000000
8      number_of_rare_classes  4764.000000
9     samples_in_rare_classes  7049.000000
10    missing_or_empty_labels     1.000000

================================================================================
LABEL ANALYSIS SAVED
================================================================================
/home/dipshikha/Music/cao/CISLR_RESEARCH/processed/label_analysis.csv
Rare-class report saved:
/home/dipshikha/Music/cao/CISLR_RESEARCH/processed/rare_classes.csv
================================================================================
STEP 4 — FINAL STATUS
================================================================================
REVIEW REQUIRED — 1 samples have missing/empty labels.

Number of classes : 4764
Total samples     : 7049
Rare classes      : 4764
Imbalance ratio   : 13.0

Previous pipeline information loaded.

CELL 3 — Load Step 2 mapping

In [4]:
# ============================================================
# CELL 3 — LOAD VIDEO MAPPING
# ============================================================
import pandas as pd
from pathlib import Path
cislr_research="/home/dipshikha/Music/cao/CISLR_RESEARCH"
mapping_file = (
    Path(cislr_research)
    / "processed"
    / "video_mapping.csv"
)

video_mapping_df = pd.read_csv(mapping_file)

print("=" * 80)
print("VIDEO MAPPING LOADED")
print("=" * 80)

print("File:", mapping_file)
print("Rows:", len(video_mapping_df))

display(
    video_mapping_df.head()
)

================================================================================
VIDEO MAPPING LOADED
================================================================================
File: /home/dipshikha/Music/cao/CISLR_RESEARCH/processed/video_mapping.csv
Rows: 7050

,uid,gloss,duration,category,video_exists,video_path
0,--7-rCNOiK0_1,branch,6.0,flora and fauna,True,/home/dipshikha/Music/cao/CISLR_v1.5-a_videos/...
1,-02y2VaVBmw,divorce petition,11.0,legal,True,/home/dipshikha/Music/cao/CISLR_v1.5-a_videos/...
2,-03Dju3yPHE,air conditioner,5.0,machine,True,/home/dipshikha/Music/cao/CISLR_v1.5-a_videos/...
3,-0Oo1kPonYQ,stapoo,6.0,sport,True,/home/dipshikha/Music/cao/CISLR_v1.5-a_videos/...
4,-0XujLX2_9I_2,application,6.0,action,True,/home/dipshikha/Music/cao/CISLR_v1.5-a_videos/...

CELL 4 — Load official test.csv

In [8]:
# ============================================================
# CELL 4 — LOAD OFFICIAL TEST SET
# ============================================================

test_file = "/home/dipshikha/Music/cao/test.csv"

official_test_df = pd.read_csv(test_file)

print("=" * 80)
print("OFFICIAL CISLR TEST SET")
print("=" * 80)

print("File:", test_file)
print("Rows:", len(official_test_df))

print("\nColumns:")
print(official_test_df.columns.tolist())

display(
    official_test_df.head()
)

================================================================================
OFFICIAL CISLR TEST SET
================================================================================
File: /home/dipshikha/Music/cao/test.csv
Rows: 2285

Columns:
['uid', 'gloss', 'duration', 'category']

             uid       gloss  duration         category
0  -NIz596Y27Q_1   severally       7.0         quantity
1  06tYXs9inPk_1      branch       6.0  flora and fauna
2  08E4Dr0zyKk_2  difference       7.0       comparator
3  0i1qCUd3BdM_1    increase       8.0       comparator
4    0p_iET-2TRw      pencil       4.0     utility item

CELL 5 — Verify required columns

In [9]:
# ============================================================
# CELL 5 — VERIFY REQUIRED COLUMNS
# ============================================================

required_mapping_columns = [
    "uid",
    "video_path"
]

required_test_columns = [
    "uid"
]

missing_mapping_columns = [
    col
    for col in required_mapping_columns
    if col not in video_mapping_df.columns
]

missing_test_columns = [
    col
    for col in required_test_columns
    if col not in official_test_df.columns
]

if missing_mapping_columns:
    raise ValueError(
        f"Missing columns in video_mapping.csv: "
        f"{missing_mapping_columns}"
    )

if missing_test_columns:
    raise ValueError(
        f"Missing columns in test.csv: "
        f"{missing_test_columns}"
    )

print("PASS — Required columns are available.")

PASS — Required columns are available.

CELL 6 — Clean UID values

In [10]:
# ============================================================
# CELL 6 — NORMALIZE UID VALUES FOR COMPARISON
# ============================================================

video_mapping_df["uid_clean"] = (
    video_mapping_df["uid"]
    .astype(str)
    .str.strip()
)

official_test_df["uid_clean"] = (
    official_test_df["uid"]
    .astype(str)
    .str.strip()
)

print("UID normalization complete.")

print(
    "Unique UIDs in complete dataset:",
    video_mapping_df["uid_clean"].nunique()
)

print(
    "Unique UIDs in official test:",
    official_test_df["uid_clean"].nunique()
)

UID normalization complete.
Unique UIDs in complete dataset: 7050
Unique UIDs in official test: 2285

CELL 7 — Verify official test UIDs exist

In [11]:
# ============================================================
# CELL 7 — OFFICIAL TEST UID EXISTENCE
# ============================================================

all_dataset_uids = set(
    video_mapping_df["uid_clean"]
)

official_test_uids = set(
    official_test_df["uid_clean"]
)

test_uids_missing_from_dataset = sorted(
    official_test_uids - all_dataset_uids
)

print("=" * 80)
print("OFFICIAL TEST UID EXISTENCE CHECK")
print("=" * 80)

print(
    "Official test UIDs:",
    len(official_test_uids)
)

print(
    "Missing from dataset:",
    len(test_uids_missing_from_dataset)
)

if len(test_uids_missing_from_dataset) == 0:

    print("\nPASS — Every official test UID exists in the dataset.")

else:

    print("\nFAIL — Test UIDs missing from dataset:")

    for uid in test_uids_missing_from_dataset[:50]:
        print(uid)

================================================================================
OFFICIAL TEST UID EXISTENCE CHECK
================================================================================
Official test UIDs: 2285
Missing from dataset: 0

PASS — Every official test UID exists in the dataset.

CELL 8 — Construct the official train set

In [12]:
# ============================================================
# CELL 8 — CONSTRUCT OFFICIAL TRAIN SET
# ============================================================

train_df = video_mapping_df[
    ~video_mapping_df["uid_clean"].isin(
        official_test_uids
    )
].copy()

test_df = video_mapping_df[
    video_mapping_df["uid_clean"].isin(
        official_test_uids
    )
].copy()

print("=" * 80)
print("OFFICIAL TRAIN / TEST PARTITION")
print("=" * 80)

print("Complete dataset :", len(video_mapping_df))
print("Train samples     :", len(train_df))
print("Test samples      :", len(test_df))

print(
    "Train + Test      :",
    len(train_df) + len(test_df)
)

================================================================================
OFFICIAL TRAIN / TEST PARTITION
================================================================================
Complete dataset : 7050
Train samples     : 4765
Test samples      : 2285
Train + Test      : 7050

CELL 9 — Train/test UID overlap

In [13]:
# ============================================================
# CELL 9 — TRAIN / TEST UID OVERLAP
# ============================================================

train_uids = set(
    train_df["uid_clean"]
)

test_uids = set(
    test_df["uid_clean"]
)

train_test_uid_overlap = sorted(
    train_uids & test_uids
)

print("=" * 80)
print("TRAIN / TEST UID OVERLAP")
print("=" * 80)

print(
    "Train unique UIDs:",
    len(train_uids)
)

print(
    "Test unique UIDs:",
    len(test_uids)
)

print(
    "Overlapping UIDs:",
    len(train_test_uid_overlap)
)

if len(train_test_uid_overlap) == 0:

    print("\nPASS — No UID appears in both train and test.")

else:

    print("\nFAIL — UID overlap detected:")

    for uid in train_test_uid_overlap[:50]:
        print(uid)

================================================================================
TRAIN / TEST UID OVERLAP
================================================================================
Train unique UIDs: 4765
Test unique UIDs: 2285
Overlapping UIDs: 0

PASS — No UID appears in both train and test.

CELL 10 — Duplicate UIDs in complete dataset

In [14]:
# ============================================================
# CELL 10 — DUPLICATE UID CHECK
# ============================================================

uid_counts = (
    video_mapping_df["uid_clean"]
    .value_counts()
)

duplicate_uids = uid_counts[
    uid_counts > 1
]

print("=" * 80)
print("DUPLICATE UID CHECK")
print("=" * 80)

print(
    "Duplicate UID values:",
    len(duplicate_uids)
)

if len(duplicate_uids) == 0:

    print("\nPASS — No duplicate UIDs.")

else:

    print("\nWARNING — Duplicate UIDs detected:")

    display(
        duplicate_uids.to_frame(
            "occurrences"
        )
    )

================================================================================
DUPLICATE UID CHECK
================================================================================
Duplicate UID values: 0

PASS — No duplicate UIDs.

CELL 11 — Check physical video path overlap

In [15]:
# ============================================================
# CELL 11 — PHYSICAL VIDEO PATH OVERLAP
# ============================================================

train_paths = set(
    train_df["video_path"]
    .astype(str)
)

test_paths = set(
    test_df["video_path"]
    .astype(str)
)

path_overlap = sorted(
    train_paths & test_paths
)

print("=" * 80)
print("PHYSICAL VIDEO PATH OVERLAP")
print("=" * 80)

print(
    "Overlapping video paths:",
    len(path_overlap)
)

if len(path_overlap) == 0:

    print(
        "\nPASS — No physical video file appears in both splits."
    )

else:

    print(
        "\nFAIL — Same physical video appears in both splits:"
    )

    for path in path_overlap[:50]:
        print(path)

================================================================================
PHYSICAL VIDEO PATH OVERLAP
================================================================================
Overlapping video paths: 0

PASS — No physical video file appears in both splits.

CELL 12 — Check duplicate video content across train/test

In [16]:
# ============================================================
# CELL 12 — EXACT VIDEO CONTENT LEAKAGE CHECK
# ============================================================

import hashlib
from pathlib import Path

def calculate_sha256(file_path, chunk_size=1024 * 1024):

    sha256 = hashlib.sha256()

    with open(file_path, "rb") as f:

        while True:

            chunk = f.read(chunk_size)

            if not chunk:
                break

            sha256.update(chunk)

    return sha256.hexdigest()

CELL 13 — Hash train and test videos

In [17]:
# ============================================================
# CELL 13 — CALCULATE TRAIN / TEST VIDEO HASHES
# ============================================================

train_hashes = {}
test_hashes = {}

print("Hashing TRAIN videos...")

for i, path in enumerate(train_paths):

    path = Path(path)

    if path.exists():

        file_hash = calculate_sha256(path)

        train_hashes.setdefault(
            file_hash,
            []
        ).append(path)

    if (i + 1) % 500 == 0:

        print(
            f"Train: {i + 1}/{len(train_paths)}"
        )


print("\nHashing TEST videos...")

for i, path in enumerate(test_paths):

    path = Path(path)

    if path.exists():

        file_hash = calculate_sha256(path)

        test_hashes.setdefault(
            file_hash,
            []
        ).append(path)

    if (i + 1) % 500 == 0:

        print(
            f"Test: {i + 1}/{len(test_paths)}"
        )

print("\nHashing complete.")

Hashing TRAIN videos...
Train: 500/4765
Train: 1000/4765
Train: 1500/4765
Train: 2000/4765
Train: 2500/4765
Train: 3000/4765
Train: 3500/4765
Train: 4000/4765
Train: 4500/4765

Hashing TEST videos...
Test: 500/2285
Test: 1000/2285
Test: 1500/2285
Test: 2000/2285

Hashing complete.

CELL 14 — Detect train/test content duplicates

In [18]:
# ============================================================
# CELL 14 — TRAIN / TEST CONTENT OVERLAP
# ============================================================

train_hash_set = set(
    train_hashes.keys()
)

test_hash_set = set(
    test_hashes.keys()
)

common_hashes = (
    train_hash_set &
    test_hash_set
)

print("=" * 80)
print("TRAIN / TEST CONTENT OVERLAP")
print("=" * 80)

print(
    "Unique train video hashes:",
    len(train_hash_set)
)

print(
    "Unique test video hashes:",
    len(test_hash_set)
)

print(
    "Identical content groups across splits:",
    len(common_hashes)
)

================================================================================
TRAIN / TEST CONTENT OVERLAP
================================================================================
Unique train video hashes: 4765
Unique test video hashes: 2285
Identical content groups across splits: 2

CELL 15 — Display potential content leakage

In [19]:
# ============================================================
# CELL 15 — CONTENT LEAKAGE REPORT
# ============================================================

if len(common_hashes) == 0:

    print(
        "PASS — No byte-identical videos were found "
        "across train and test."
    )

else:

    print(
        "WARNING — Potential content leakage detected."
    )

    print(
        "\nIdentical train/test video groups:"
    )

    for file_hash in common_hashes:

        print("\nSHA-256:", file_hash)

        print("TRAIN:")

        for path in train_hashes[file_hash]:
            print("  ", path)

        print("TEST:")

        for path in test_hashes[file_hash]:
            print("  ", path)

WARNING — Potential content leakage detected.

Identical train/test video groups:

SHA-256: c5dcb5569340a403e8905350846df0bd6316497cba1e88dfbb69feeb00bef3a3
TRAIN:
   /home/dipshikha/Music/cao/CISLR_v1.5-a_videos/TR30xmE3v0s.mp4
TEST:
   /home/dipshikha/Music/cao/CISLR_v1.5-a_videos/ntsopMo8ABU.mp4

SHA-256: 3cae693c38ce593e9244d57eab51a776b1325b7c933c21d89982280955b00cac
TRAIN:
   /home/dipshikha/Music/cao/CISLR_v1.5-a_videos/D9ihUabRKIQ_2.mp4
TEST:
   /home/dipshikha/Music/cao/CISLR_v1.5-a_videos/wwQV7dGvw0s_2.mp4

CELL 16 — Check official test label consistency

In [20]:
# ============================================================
# CELL 16 — TEST LABEL CONSISTENCY
# ============================================================

dataset_labels = (
    video_mapping_df[
        ["uid_clean", "gloss"]
    ]
    .drop_duplicates("uid_clean")
)

test_labels = (
    official_test_df[
        ["uid_clean", "gloss"]
    ]
    .drop_duplicates("uid_clean")
)

label_check_df = test_labels.merge(
    dataset_labels,
    on="uid_clean",
    how="left",
    suffixes=(
        "_test_csv",
        "_dataset"
    )
)

label_mismatch_df = label_check_df[
    label_check_df["gloss_test_csv"]
    !=
    label_check_df["gloss_dataset"]
].copy()

print("=" * 80)
print("OFFICIAL TEST LABEL CONSISTENCY")
print("=" * 80)

print(
    "Label mismatches:",
    len(label_mismatch_df)
)

if len(label_mismatch_df) == 0:

    print(
        "\nPASS — Official test labels match dataset labels."
    )

else:

    print(
        "\nFAIL — Label mismatch detected:"
    )

    display(label_mismatch_df)

================================================================================
OFFICIAL TEST LABEL CONSISTENCY
================================================================================
Label mismatches: 0

PASS — Official test labels match dataset labels.

CELL 17 — Potential leakage summary

In [21]:
# ============================================================
# CELL 17 — POTENTIAL LEAKAGE SUMMARY
# ============================================================

potential_leakage = {
    "train_test_uid_overlap": len(
        train_test_uid_overlap
    ),

    "train_test_path_overlap": len(
        path_overlap
    ),

    "train_test_identical_content": len(
        common_hashes
    ),

    "duplicate_uids_in_dataset": len(
        duplicate_uids
    ),

    "official_test_uids_missing": len(
        test_uids_missing_from_dataset
    ),

    "test_label_mismatches": len(
        label_mismatch_df
    )
}

leakage_summary_df = pd.DataFrame(
    potential_leakage.items(),
    columns=[
        "check",
        "count"
    ]
)

print("=" * 80)
print("POTENTIAL LEAKAGE SUMMARY")
print("=" * 80)

display(leakage_summary_df)

================================================================================
POTENTIAL LEAKAGE SUMMARY
================================================================================

                          check  count
0        train_test_uid_overlap      0
1       train_test_path_overlap      0
2  train_test_identical_content      2
3     duplicate_uids_in_dataset      0
4    official_test_uids_missing      0
5         test_label_mismatches      0

CELL 18 — Final PASS / FAIL

In [22]:
# ============================================================
# CELL 18 — STEP 5 FINAL STATUS
# ============================================================

critical_failures = (
    len(test_uids_missing_from_dataset)
    +
    len(train_test_uid_overlap)
    +
    len(path_overlap)
    +
    len(common_hashes)
    +
    len(label_mismatch_df)
)

print("=" * 80)
print("STEP 5 — FINAL STATUS")
print("=" * 80)

if critical_failures == 0:

    print("STEP 5 STATUS: PASS")
    print()
    print("✓ Official test UIDs are valid")
    print("✓ No train/test UID overlap")
    print("✓ No physical video path overlap")
    print("✓ No byte-identical video content across splits")
    print("✓ Official test labels are consistent")

else:

    print("STEP 5 STATUS: REVIEW REQUIRED")
    print()
    print(
        "Critical issues detected:",
        critical_failures
    )

print("=" * 80)

================================================================================
STEP 5 — FINAL STATUS
================================================================================
STEP 5 STATUS: REVIEW REQUIRED

Critical issues detected: 2
================================================================================

CELL 19 — Save split information

In [25]:
# ============================================================
# CELL 19 — SAVE SPLIT MEMBERSHIP
# ============================================================

split_membership_df = video_mapping_df[
    [
        "uid",
        "uid_clean",
        "gloss",
        "video_path"
    ]
].copy()

split_membership_df["split"] = (
    split_membership_df["uid_clean"]
    .apply(
        lambda uid:
        "test"
        if uid in official_test_uids
        else "train"
    )
)

split_file = (
    Path(cislr_research)
    / "processed"
    / "split_membership.csv"
)

split_membership_df.to_csv(
    split_file,
    index=False
)

print("=" * 80)
print("SPLIT MEMBERSHIP SAVED")
print("=" * 80)

print(split_file)

================================================================================
SPLIT MEMBERSHIP SAVED
================================================================================
/home/dipshikha/Music/cao/CISLR_RESEARCH/processed/split_membership.csv

CELL 20 — Save leakage report

In [27]:
# ============================================================
# CELL 20 — SAVE LEAKAGE REPORT
# ============================================================

leakage_file = (
    Path(cislr_research)
    / "processed"
    / "split_leakage_report.csv"
)

leakage_summary_df.to_csv(
    leakage_file,
    index=False
)

print("Leakage report saved:")
print(leakage_file)

Leakage report saved:
/home/dipshikha/Music/cao/CISLR_RESEARCH/processed/split_leakage_report.csv

CELL 21 — Save official test verification

In [29]:
# ============================================================
# CELL 21 — SAVE OFFICIAL TEST VERIFICATION
# ============================================================

test_verification_df = test_df.copy()

test_verification_df["official_test"] = True

test_verification_file = (
    Path(cislr_research)
    / "processed"
    / "official_test_verified.csv"
)

test_verification_df.to_csv(
    test_verification_file,
    index=False
)

print("Official test verification saved:")
print(test_verification_file)

Official test verification saved:
/home/dipshikha/Music/cao/CISLR_RESEARCH/processed/official_test_verified.csv

CELL 22 — Final report

In [30]:
# ============================================================
# CELL 22 — FINAL STEP 5 REPORT
# ============================================================

print()
print("=" * 80)
print("CISLR — STEP 5 FINAL REPORT")
print("=" * 80)

print(f"Complete dataset        : {len(video_mapping_df):,}")
print(f"Train samples           : {len(train_df):,}")
print(f"Official test samples   : {len(test_df):,}")
print(f"Unique train UIDs       : {len(train_uids):,}")
print(f"Unique test UIDs        : {len(test_uids):,}")

print()
print("VERIFICATION")
print("-" * 80)

print(
    f"Missing official test UIDs : "
    f"{len(test_uids_missing_from_dataset)}"
)

print(
    f"Train/test UID overlap     : "
    f"{len(train_test_uid_overlap)}"
)

print(
    f"Physical path overlap      : "
    f"{len(path_overlap)}"
)

print(
    f"Identical content overlap  : "
    f"{len(common_hashes)}"
)

print(
    f"Duplicate UIDs             : "
    f"{len(duplicate_uids)}"
)

print(
    f"Test label mismatches      : "
    f"{len(label_mismatch_df)}"
)

print()
print("=" * 80)

if critical_failures == 0:
    print("STEP 5 STATUS: PASS")
else:
    print("STEP 5 STATUS: REVIEW REQUIRED")

print("=" * 80)

================================================================================
CISLR — STEP 5 FINAL REPORT
================================================================================
Complete dataset        : 7,050
Train samples           : 4,765
Official test samples   : 2,285
Unique train UIDs       : 4,765
Unique test UIDs        : 2,285

VERIFICATION
--------------------------------------------------------------------------------
Missing official test UIDs : 0
Train/test UID overlap     : 0
Physical path overlap      : 0
Identical content overlap  : 2
Duplicate UIDs             : 0
Test label mismatches      : 0

================================================================================
STEP 5 STATUS: REVIEW REQUIRED
================================================================================